[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Development context
[context.development]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 