version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # This will load environment variables from .env file
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev 