// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktktwfllgtuwunoutage.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0a3R3ZmxsZ3R1d3Vub3V0YWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMzk1OTIsImV4cCI6MjA1NDgxNTU5Mn0.B69T22bHfwy7dz10d-7g1cxovCAgWM4RVVXJ3hEvbWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);